import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import TanstackProvider from "@/lib/TanstackProvider";
import { AuthProvider } from "@/context/auth-provider";
import { getCategories } from "@/lib/server-api";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categoriesResponse = await getCategories()
  const categories = categoriesResponse.data.data.slice(0, 5);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanstackProvider>
          <AuthProvider>
            <div className="min-h-screen flex flex-col">
              <Header categories={categories} />
              <main className="flex-grow">{children}</main>
              <Footer categories={categories} />
              <Toaster />
            </div>
          </AuthProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
